url: http://www.asperger.cz
baseurl: .

# Site settings
title: asperger.cz
email: info@asperger.cz
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Martin Urbanec
  pic: 1
  position: Administrátor
  email: martin@asperger.cz
  social:
    - title: twitter
      url: https://twitter.com/martin_urbanec
    - title: facebook
      url: https://www.facebook.com/martin.urbanec.545
 #   - title: stack-overflow
#      url: #

- name: Depresorka
  pic: 1
  position: Redaktor
  social:
#    - title: twitter
#      url: #
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100008936071964&fref=ts
 #   - title: linkedin
#      url: #

- name: Tomáš Kourek
  pic: 1
  position: Redaktor

- name: Michal Roškaňuk
  pic: 1
  position: Poradce
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/michal.obecny1?fref=ts
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aspie12321
  - title: facebook
    url: http://facebook.com/aspie12321
#  - title: stack-overflow
#    url: #
#  - title: bitbucket 
#    url: #
#  - title: github
#    url: #

# Postal address (add as many lines as necessary)
#address:
#  - line: #

# Build settings
markdown: kramdown
permalink: pretty
