url: http://www.asperger.cz
baseurl: .

# Site settings
title: asperger.cz
email: info@asperger.cz
description: ""

author :
  email: info@asperger.cz

# Color settings (hex-codes without the leading hash-tag)
color:
	primary: fed136
	secondary: fec503
	secondary-dark: 333
# Team names, titles and social links
people:
- name: Martin Urbanec
  pic: 3
  position: Administrátor
  email: martin@asperger.cz
  social:
    - title: twitter
      url: https://twitter.com/martin_urbanec
    - title: facebook
      url: https://www.facebook.com/martin.urbanec.545

#- name: Depresorka
#  pic: 4
#  positionn: Redaktor
#  email: majda@asperger.cz
#  social:
#    - title: facebook
#      url: https://www.facebook.com/profile.php?id=100008936071964&fref=ts

#- name: Tomáš Kourek
#  pic: 4
#  position: Redaktor
#  email: tomas@asperger.cz
#  social:
#    - title: facebook
#    url: url

- name: Adam Naicler
  pic: 4
  position: Moderátor
  email: adam@asperger.cz

- name: Michal Struhár
  pic: 2
  position: Poradce
  email: michal@asperger.cz
  social:
    - title: facebook
      url: https://www.facebook.com/michal.struhar.79?fref=ufi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/aspie12321
  - title: facebook
    url: http://facebook.com/aspie12321
#  - title: stack-overflow
#    url: #
#  - title: bitbucket 
#    url: #
#  - title: github
#    url: #

# Postal address (add as many lines as necessary)
#address:
#  - line: #

# Build settings
markdown: kramdown
permalink: pretty
